version: '3'
services:
  web:
    image: "novskytech/djangoproject"
    hostname: web
    environment:
      - SECRET_KEY
  nginx:
    depends_on:
      - web
    image: "novskytech/djangonginx"
    hostname: nginx
    ports:
      - '4000:80'
