version: '3'
services:
  web:
    build:
      context: ./myproject
    ports:
      - '8001:8000'
  nginx:
    depends_on:
      - web
    build:
      context: ./nginx
    ports:
      - '3050:80'
    volumes:
      - /Users/jkonovsky/development/DjangoElasticBeanstalkTemplate/myproject/staticfiles:/staticfiles
      # should update this to a relative instead of a relative path
