version: '3'
services:
  web:
    build:
      context: ./myproject
      dockerfile: Dockerfile.dev
    ports:
      - '8001:8000'
  nginx:
    depends_on:
      - web
    build:
      context: ./nginx
    ports:
      - '80:80'
    volumes:
      - ./myproject/prod_static:/static
