version: '3'
services:
  web:
    build:
      context: ./myproject
    ports:
      - '8001:8000'
  nginx:
    depends_on:
      - web
    build:
      context: ./nginx
    ports:
      - '3050:80'
    volumes:
      - /Users/jkonovsky/development/DjangoElasticBeanstalkTemplate/myproject/staticfiles:/staticfiles
  # debug using just the single container, should be able to access style.css from the url
  # probably should not manually move the files
  # https://forum.djangoproject.com/t/mime-type-text-html-is-not-a-supported-404-static-files-nginx-uwsgi-production/10459/3
