version: '3'
services:
  web:
    image: "novskytech/djangoproject"
    mem_limit: 128m
    ports:
      - '8001:8000'
    hostname: web
  nginx:
    depends_on:
      - web
    image: "novskytech/djangoproject"
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
    volumes:
      - ./myproject/prod_static:/static
