version: '3'
services:
  web:
    build:
      context: ./myproject
    ports:
      - '8001:8000'
    environment:
      - SECRET_KEY
  nginx:
    depends_on:
      - web
    build:
      context: ./nginx
    ports:
      - '80:80'
